### ISSUE TITLE
Faire une page par commission

### ISSUE THREAD

**Issue by clairezed** [clairezed/nuit-debout-epinal#2]
- [x] description
- [x] photos
- [x] channel
- [ ] class active sur menu "Commissions"

**Comment by EmmanuelleL** [comment]
photo ok
channel ok

**Comment by EmmanuelleL** [comment]
descriptions : 
antipub : réflexions et actions autour de l'opposition à l'omniprésence de la publicité.
convergence des luttes : synchronisation des actions au sein de la nuit debout et en lien avec le tissu associatif existant
musique : gestion et organisation de concerts et d'animations musicales
projet de société : réflexions et débats autour de la société

**Comment by EmmanuelleL** [comment]
dernière description : 
La langue de bois est un principe fondamental de ce qui gouverne le système même de notre langage. Constamment utilisée lors de discours officiels importants, meetings politiques, colloques divers, elle permet de mettre en place un dialecte rhétorique donnant l’impression de dire des choses alors que rien ne se dit concrètement. Son fonctionnement est simple, consistant en l’emploi de quelques mots-clés abstraits se présentant comme termes à sens profond. Pour exemples : Diagnostic partagé, Propriété, Partenariat, Démocratie, Habitants, Développement, Projet, Proximité, Acteurs, Local, Contrat, Biens communs, Interculturel, Lien social, mondialisation… Placez quelques uns de ces mots dans une phrase, ou mieux, construisez des phrases principalement avec ces mots, et vous rejoindrez l’emblème de ce fabuleux jargon institutionnel que l’on nomme la langue de bois.
