### ISSUE TITLE
Page revue de presse

### ISSUE THREAD

**Issue by clairezed** [clairezed/nuit-debout-epinal#3]

**Comment by EmmanuelleL** [comment]
http://www.actu88.fr/nuit-debout-se-poursuit-demain-soir/
http://www.vosgesmatin.fr/edition-d-epinal/2016/04/22/vosges-epinal-passe-sa-premiere-nuit-debou
http://www.magnumlaradio.com/economie-societe/article/7660-epinal-nuit-debout-s-installe-place-des-vosges.html
https://www.facebook.com/141133179273864/photos/pcb.994370003950173/994369450616895/?type=3
http://epinalinfos.fr/2016/04/nuit-debout-sinstalle-place-vosges/
http://www.actu88.fr/nuit-debout-se-poursuit-demain-soir
